export { Home } from './Home'
export { HomeOutline } from './HomeOutline'
export { LogoutOutline } from './LogoutOutline'
export { Menu } from './Menu'
export { MenuOutline } from './MenuOutline'
export { Person } from './Person'
export { PersonOutline } from './PersonOutline'
