apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tavistoica/auth
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: facebook
                  key: FACEBOOK_CLIENT_ID
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook-secret
                  key: FACEBOOK_CLIENT_SECRET
            - name: FACEBOOK_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: facebook-callback
                  key: FACEBOOK_CALLBACK_URL
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: salt
                  key: SALT
            - name: REFRESH_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: refresh-token-key
                  key: REFRESH_TOKEN_PRIVATE_KEY
            - name: ACCESS_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: access-token-key
                  key: ACCESS_TOKEN_PRIVATE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3001
