name: tests-tickets

on:
  pull_request:
    paths:
      - "tickets/**"
     branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
