name: test-auth

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: cd auth && npm install && npm run test:ci
        env:
          BRANCH_PREFIX: "skip-*"
          PULL_REQUEST_BRANCH: "main"
